Main svc
AlekseyKudrin/java-explore-with-me pull request #5
Opened 2023-06-15 12:41 UTC by AlekseyKudrin

2023-06-18 09:49 UTC, TomattmanYandex requested changes
Привет, работа отличная, из вопросов только стиль кода, 
комменты я оставил, но не везде.

Два момента которые вынесу отдельно
1) пакеты в stat-server
следует добавить пакет stat  чтобы было ru.practicum.stat в нем стартовый класс  а в нем уже добавить еще пакет допустим statistic в котором будут все остальные классы
2) пакеты при разбиении на пакеты по фичам, обычно при таком построении пакетов, не делают дополнительные подпакеты по функционалу, допустим есть пакет category и все что касается категорий, находится прямо в этом пакете, без подпакетов, исключение, если есть како йто функционал, который является подфункионалом какой то другой фичи, тогда для него можно создать подпакет, поэтому стоит немного подвигать по пакетам классы
3) тоже по пакетам, (к текущей работе не относится, из-за предыдущего пункта) обычно разделяют классы моделей, классы дто, и классы мапперов из можелей в дто

подпакеты в пакетах

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/admin/AdminController.java
> +    public void deleteUser(
не очень читаемый с точки зрения переносов код

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/admin/AdminController.java
> +    public void deleteCompilation(
тут тоже

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/admin/AdminController.java
> +    public CategoryDto createCategory(
и тут

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/admin/AdminController.java
> +    public void deleteUser(
кажется длинны строки стандартной должно хватить для размещения в одну строку без переносов

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/admin/service/impl/AdminServiceImpl.java
> +    private final UserServiceImpl userService;
Если на все сервисы есть интерфейс, то почему бы нам не инжектить именно по нему

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/category/CategoryController.java
> +    private final CategoryServiceImpl categoryService;
аналогично

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/category/CategoryController.java
> +            @PathVariable Integer catId
аналогично про переносы

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/category/dao/CategoryRepository.java
> +package ru.practicum.category.dao;
dao и репозитории немного отличаются между собой, поэтому при использовании jpa репозиториев лучше пакет с ними так и называть repo, repository

2023-06-18 09:49 UTC, TomattmanYandex commented on main-server/src/main/java/ru/practicum/event/service/impl/EventServiceImpl.java
> +            if (event.getAnnotation().length() < 20 || event.getAnnotation().length() > 2000) {
Почему бы не сделать отдельный метод который провалидирует все поля, и вызвать его в началае, чтобы структура метода была линейнее, 
1) проверили валидацию, если не валидно кинули ошибку
2) если валидно то обновляем поля

2023-06-18 20:36 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/admin/AdminController.java
> +    public void deleteUser(
оставил

2023-06-18 20:37 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/admin/AdminController.java
> +    public void deleteCompilation(
оставил

2023-06-18 20:37 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/admin/AdminController.java
> +    public CategoryDto createCategory(
оставил

2023-06-18 20:38 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/admin/service/impl/AdminServiceImpl.java
> +    private final UserServiceImpl userService;
в сервисах присутствуют методы не объявленные в интерфейсах

2023-06-18 20:38 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/category/CategoryController.java
> +    private final CategoryServiceImpl categoryService;
в сервисах присутствуют методы не объявленные в интерфейсах

2023-06-18 20:38 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/category/CategoryController.java
> +            @PathVariable Integer catId
оставил

2023-06-18 20:38 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/event/service/impl/EventServiceImpl.java
> +            if (event.getAnnotation().length() < 20 || event.getAnnotation().length() > 2000) {
оставил

2023-06-19 08:24 UTC, TomattmanYandex requested changes
Привет, ни по одному коменту ничего не исправлено, 
Они не по функционалу а по читаемости кода, но читаемость кода, это важный момент относящийся к поддерживаемости и качеству самого кода, 
Пройдись пожалуйста еще раз по предыдущим комментариям
Переносы можно и не трогать, чтобы везде было одинаково, но разбиение по пакетам, моменты с валидацией, и сервисами стоит исправить

2023-06-19 10:19 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/admin/service/impl/AdminServiceImpl.java
> +    private final UserServiceImpl userService;
Исправил

2023-06-19 10:19 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/category/CategoryController.java
> +    private final CategoryServiceImpl categoryService;
Исправил

2023-06-19 10:19 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/category/dao/CategoryRepository.java
> +package ru.practicum.category.dao;
Переименовал

2023-06-19 10:20 UTC, AlekseyKudrin commented on main-server/src/main/java/ru/practicum/event/service/impl/EventServiceImpl.java
> +            if (event.getAnnotation().length() < 20 || event.getAnnotation().length() > 2000) {
Вынес

2023-06-20 08:43 UTC, TomattmanYandex approved these changes
Привет, по пакетам, (из общего комента замечание) тоже ничего не сделано
1)  обычно базовая структура пакетов в проекте это groupId + artifactId
это делается для уникальности имен классов, самый просто пример, у тебя в обоих подпроектах есть обработчик ошибок ErrorHandler в пакете ru.practicum.exceptionHandler;
если использовать эти проекты как библиотеку, то возникает проблема, как определить какой использовать
вклчюение artifactId исправило бы эту проблему
2) при стратегии именования пакетов по фичам, обычно не создаются подпакеты под отдельный тип классов, потому что чаще всего это пакеты для одного класса, и смысла это почти не добавляет, т.е. создается пакет location и в нем без подпакетов уже все классы
3) модели и дто это разные вещи, модели имеют отношение к базе данных, дто к передаче данных между уровнями, и если создаешь пакет под хранение моделей, не надо туда добавлять также dto

2023-06-20 10:29 UTC, merged